### ISSUE TITLE
[Feat] HomeScreen

### ISSUE THREAD

**Issue by angel-penchev** [braind3d/DRUN#19]
**Describe the feature you'd like**
This will be the primary screen of the app.

The following should be added:
- [x] Similar to Viber and other messaging apps, a prompt for allowing access to contacts should be displayed on the first run.
- [x] Afterwards, every contact phone number is checked against the Firebase document for any matches and displayed in the app's list. 
- [x] If a contact is pressed, the user should be redirected to a MessagesScreen (#20), where he can chat/send orders with the contact of choice.
- [x] A settings button should be present at the top right corner of the screen, redirecting to the SettingsScreen (#21).
- [x] Coin balance button on the top left, which when pressed should open a BalanceDialog containing options for depositing or cashing out (#24).

**Additional context**
- Design mock-up 
     ![HomeScreen](https://user-images.githubusercontent.com/26301867/94678753-a910f200-0327-11eb-80a7-8493d5d206d4.png)
- Resources
     - Article: [How To Access Contacts On Your Flutter App](https://medium.com/xenon-labs/how-to-access-contacts-in-your-flutter-app-3f0158ce1ee7)
     - Video: [I built a chat app in 7 minutes with React & Firebase](https://youtu.be/zQyrwxMPm88)
