### ISSUE TITLE
[Feat] SettingsScreen

### ISSUE THREAD

**Issue by angel-penchev** [braind3d/DRUN#21]
**Describe the feature you'd like**
A settings screen with the name of the user logged in at the top and options below.
The following are the essential options:
- [ ] Top-up/Cash-out (#24)
- [ ] Logout

And these are the options, it is highly recommended we implement:
- [ ] Login with Discord (#26)
- [ ] Profile picture change (#28)
- [ ] Dark mode (#29)

**Additional context**
- Design mock-up
   ![SettingsScreen](https://user-images.githubusercontent.com/26301867/94691574-23e30880-033a-11eb-896b-2374f8c2ab81.png)

**Comment by angel-penchev** [comment]
As the whole app will be refactored, this will be included in another issue.
